server:
  port: 9090
  display-name: cdubbo-consumer

spring:
  dubbo:
    application:
      name: dubbo-consumer
    registry:
      address: zookeeper://10.168.17.75:2181
    scan: com.reapal.dubbo.consumer